[build]
  publish = "test-vue-app/dist"
  command = "npm install --prefix test-vue-app && npm run build --prefix test-vue-app"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
